/**
 ******************************************************************************
 * @file    main.c
 * @author  Auto-generated by STM32CubeIDE
 * @version V1.0
 * @brief   Default main function.
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f0xx.h"
#include "sct.h"

int main(void)
{
	sct_init();

	//	sct_led(0x7A5C36DE);
	while(1)
	{
		uint32_t j,k;
		for(j=0; j<1000; j=j+111)
		{
			sct_value(j);
			for(k=0; k<250000; k++)
			{

			}
		}
		if (j == 999)
		{
			j = 0;
		}
	}
}


