/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f0xx.h"

int main(void)
{
	uint8_t pole[] = {1,0,1,0,1,0,0,1,1,1,0,1,1,1,0,1,1,1,0,0,1,0,1,0,1,0,0,0,0,0,0,0};
	uint32_t value = 0b10101001110111011100101010000000;
	uint32_t temp =  0;
	uint32_t check = 0;
	RCC->AHBENR |= RCC_AHBENR_GPIOAEN;
	GPIOA->MODER |= GPIO_MODER_MODER5_0;
	uint8_t i = 0;
	check = value;
	//first program
//    while(1)
//    {
//    	GPIOA->ODR ^= (1<<5);
//    	for (volatile uint32_t i = 0; i < 250000; i++) {
//    	}
//    }
	//Second program
//	while(1)
//	{
//	    if(pole[i] == 1)
//	    {
//	      GPIOA->BSRR = (1<<5); // set
//	    }
//	    if(pole[i] == 0)
//	    {
//	      GPIOA->BRR = (1<<5); // reset
//	    }
//	    i++;
//		for (volatile uint32_t k = 0; k < 170000; k++)
//		{
//		}
//		if (i==33)
//			i=0;
//	}
	//Third program
	while(1)
	{
      if (check >= 0b10000000000000000000000000000000)
    	  GPIOA->BSRR = (1<<5); // set
      else
    	  GPIOA->BRR = (1<<5); // reset
      for (volatile uint32_t k = 0; k < 170000; k++)
      {
      }
      i++;
	  if (i==33)
	  {
		check = value;
	    i=0;
	  }
	  check = check << 1;
	}
}

